ML Output for /home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103D6B64A9D11BFADCD674B3BE46528EA88FBEA4ADFB1A33FC9CEC29479.apk: 
[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 573ms/step
[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m1s[0m 573ms/step
File: classes.dex.png, Prediction: 0.3373, Label: Clean

ClamAV Output saved to /home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479_clamav.txt
Debug: Infected files: 1
Traceback (most recent call last):
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 170, in <module>
    main(apk_file_path, extract_folder, file_hash)
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 157, in main
    move_files_when_ready(extract_folder, file_hash, f"Result: {final_result}")
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 69, in move_files_when_ready
    os.rename(html_file_path, os.path.join(reports_html_dir, f"{file_hash}.html"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479.html' -> '/var/www/html/reports_html/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479.html'
e empty until you train or evaluate the model.
Traceback (most recent call last):
  File "/home/khanhpvse160256/code_static/machine_learning_ccn.py", line 88, in <module>
    main(APK_PATH)
  File "/home/khanhpvse160256/code_static/machine_learning_ccn.py", line 76, in main
    shutil.rmtree(EXTRACT_PATH)
  File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/khanhpvse160256/extract_apk_ML'

machine_learning_ccn.py failed for /home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103D6B64A9D11BFADCD674B3BE46528EA88FBEA4ADFB1A33FC9CEC29479.apk
ClamAV Output saved to /home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479_clamav.txt
Debug: Infected files: 1
Traceback (most recent call last):
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 170, in <module>
    main(apk_file_path, extract_folder, file_hash)
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 157, in main
    move_files_when_ready(extract_folder, file_hash, f"Result: {final_result}")
  File "/home/khanhpvse160256/code_static/parallel_2.py", line 69, in move_files_when_ready
    os.rename(html_file_path, os.path.join(reports_html_dir, f"{file_hash}.html"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/khanhpvse160256/apk_analysis/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479.html' -> '/var/www/html/reports_html/03861103d6b64a9d11bfadcd674b3be46528ea88fbea4adfb1a33fc9cec29479.html'
